# Generated by Django 4.1.7 on 2023-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_alter_incidentdetails_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdetails',
            name='incident_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
